import { writeFile } from 'node:fs/promises';

// Everything about how the /admin editing surface is treated in a PRODUCTION
// build, in one place — imported only by astro.config.mjs (build tooling, never
// client code).
//
// Editing is dev-only (see src/lib/permissions.js), so a production build is
// always a read-only archive. That means `astro build` always:
//
//   1. Drops the admin-only client islands from the bundle. Astro bundles any
//      `client:only` island it finds by scanning templates, regardless of whether
//      a route actually renders it (withastro/astro#4564) — so the editor's
//      ~540KB of CodeMirror would otherwise ship as an orphaned, never-served
//      chunk even though /admin isn't built. We swap each for an empty component.
//   2. Writes a `_redirects` rule bouncing /admin/* to the read view — the /admin
//      pages aren't built, so those URLs would otherwise 404.
//
// `astro dev` is unaffected: the stub plugin is scoped to `build` and the
// _redirects hook only runs on build, so dev serves the live /admin routes.
//
// ── To exclude another admin-only client module from production builds, add its
//    import-path suffix to ADMIN_ONLY_MODULES below. ──
const ADMIN_ONLY_MODULES = [
  'components/EntryEditor.jsx',
  'components/AdminEdit.jsx',
];

// The /admin/* → read-view bounce written into dist/_redirects (a Cloudflare Pages
// / Netlify build-output convention). 302, not 301: the redirect is temporary, so
// nothing caches it as permanent. `astro dev` doesn't consult this file — it serves
// the live /admin routes.
const ADMIN_REDIRECTS = `# Generated by src/lib/adminBuild.js. /admin is a dev-only editing surface that
# isn't built in production, so bounce its URLs to home instead of 404ing. (The
# edit page is /admin/edit?post=<id> — a query, which path-based rules can't map to
# a specific entry — so everything just goes home.)
/admin/*  /  302
`;

// Vite plugin: replace each admin-only module with an empty component. `apply:
// 'build'` scopes it to `astro build` (dev serves the real modules); `enforce:
// 'pre'` runs it before Astro's own resolvers.
function stubAdminModules() {
  const prefix = '\0admin-stub:';
  return {
    name: 'stub-admin-only-modules',
    apply: 'build',
    enforce: 'pre',
    resolveId(source) {
      return ADMIN_ONLY_MODULES.some((m) => source.endsWith(m)) ? prefix + source : null;
    },
    load(id) {
      return id.startsWith(prefix) ? 'export default function AdminStub() { return null; }' : null;
    },
  };
}

// Astro integration bundling both behaviors, so astro.config just lists it once.
export function adminBuild() {
  return {
    name: 'admin-build',
    hooks: {
      'astro:config:setup': ({ updateConfig }) => {
        updateConfig({ vite: { plugins: [stubAdminModules()] } });
      },
      'astro:build:done': async ({ dir }) => {
        // The /admin pages are never built in production, so bounce their URLs.
        // `dir` is the output directory URL, so this lands at dist/_redirects.
        await writeFile(new URL('_redirects', dir), ADMIN_REDIRECTS, 'utf8');
      },
    },
  };
}
