import { writeFile } from 'node:fs/promises';

// Everything about how the /admin editing surface is treated in a PRODUCTION
// build, in one place — imported only by astro.config.mjs (build tooling, never
// client code).
//
// Editing is dev-only unless PUBLIC_ENABLE_EDITING=true is set for the build (see
// src/lib/capabilities.js). When it's OFF (the default), a production build:
//
//   1. Drops the admin-only client islands from the bundle. Astro bundles any
//      `client:only` island it finds by scanning templates, regardless of whether
//      a route actually renders it (withastro/astro#4564) — so the editor's
//      ~540KB of CodeMirror would otherwise ship as an orphaned, never-served
//      chunk even though /admin isn't built. We swap each for an empty component.
//   2. Writes a `_redirects` rule bouncing /admin/* to the read view — the /admin
//      pages aren't built, so those URLs would otherwise 404.
//
// When editing is ON, both steps are skipped: the /admin pages are built, the
// editor stays in the bundle, and nothing is redirected. One switch, one file.
//
// ── To exclude another admin-only client module from production builds, add its
//    import-path suffix to ADMIN_ONLY_MODULES below. ──
const ADMIN_ONLY_MODULES = [
  'components/EntryEditor.jsx',
];

// The /admin/* → read-view bounce written into dist/_redirects (a Cloudflare Pages
// / Netlify build-output convention). 302, not 301: the redirect is temporary, so
// nothing caches it as permanent if editing is later enabled and /admin becomes
// real. `astro dev` doesn't consult this file — it serves the live /admin routes.
const ADMIN_REDIRECTS = `# Generated by src/lib/adminBuild.js. /admin is a dev-only editing surface that
# isn't built in production, so bounce its URLs to the read view instead of 404ing.
/admin/posts/*  /posts/:splat  302
/admin/*        /              302
`;

// Whether THIS build should ship the editing surface. Read from process.env
// because this runs in the Node build config, where import.meta.env isn't Astro's
// populated one — hence the "set it as a real env var" note in capabilities.js.
const editingEnabled = () => process.env.PUBLIC_ENABLE_EDITING === 'true';

// Vite plugin: replace each admin-only module with an empty component. `apply:
// 'build'` scopes it to `astro build` (dev serves the real modules); `enforce:
// 'pre'` runs it before Astro's own resolvers. A no-op when editing is enabled.
function stubAdminModules() {
  const prefix = '\0admin-stub:';
  return {
    name: 'stub-admin-only-modules',
    apply: 'build',
    enforce: 'pre',
    resolveId(source) {
      if (editingEnabled()) return null;
      return ADMIN_ONLY_MODULES.some((m) => source.endsWith(m)) ? prefix + source : null;
    },
    load(id) {
      return id.startsWith(prefix) ? 'export default function AdminStub() { return null; }' : null;
    },
  };
}

// Astro integration bundling both behaviors, so astro.config just lists it once.
export function adminBuild() {
  return {
    name: 'admin-build',
    hooks: {
      'astro:config:setup': ({ updateConfig }) => {
        updateConfig({ vite: { plugins: [stubAdminModules()] } });
      },
      'astro:build:done': async ({ dir }) => {
        // Only bounce /admin when its pages weren't built. `dir` is the output
        // directory URL, so this lands at dist/_redirects.
        if (editingEnabled()) return;
        await writeFile(new URL('_redirects', dir), ADMIN_REDIRECTS, 'utf8');
      },
    },
  };
}
